package:
    name: cmor
    version: 3.3.1.npy{{ numpy }}

source:
    git_rev: master
    git_url: git://github.com/PCMDI/cmor.git

build:
  number: 0

test:
  requires:
    - python
    - gcc [osx]
  imports:
    - cmor

requirements:
  build:
    - python {{ python }}
    - ossuuid 1.6.2
    - udunits2
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - numpy {{ numpy }}.*
    - gcc [osx]
  run:
    - python {{ python }}
    - ossuuid 1.6.2
    - udunits2
    - libnetcdf 4.4.*
    - numpy {{ numpy }}.*
    - cdms2
    - gcc [osx]
    - hdf5 1.8.18|1.8.18.*

about:
    home:  http://gitub.com/PCMDI


