package:
    name: cmor
    version: 3.2.8

source:
    git_rev: master
    git_url: git://github.com/PCMDI/cmor.git

build:
  number: 0

test:
  requires:
    - python
    - libgcc [osx]
  imports:
    - cmor

requirements:
  build:
    - python 
    - ossuuid 1.6.2.*
    - udunits2
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - numpy {{ NPY_VER }}
    - libgcc [osx]
  run:
    - python
    - ossuuid 1.6.2.*
    - udunits2
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
    - numpy {{ NPY_VER }}
    - cdms2
    - libgcc [osx]

about:
    home:  http://github.com/PCMDI


