name: CMOR Nightly Build
run-name: CMOR Nightly Build
on: [push]

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      matrix:
        os: [macos-14]
        python_version: [3.11]
    runs-on: ${{ matrix.os }}
    env:
      OS: osx_arm64
      MINICONDA_INSTALLER_URL: https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
      PROJECT_DIR: workdir/macos
      C_COMPILER: clang_osx-64
      FORTRAN_COMPILER: gfortran_osx-64
    steps:
      - name: Setup Miniconda
        run: |
          curl -L $MINICONDA_INSTALLER_URL -o miniconda.sh
          bash miniconda.sh -b -p miniconda
          source miniconda/etc/profile.d/conda.sh
          python -V
